"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4mqvg5kc1%61hf9(4tscj6i)=3btgv5u18(4gr4d*7rcweu6ye'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ["localhost","192.168.26.137"]
# ALLOWED_HOSTS = ["127.0.0.1","192.168.26.137"]
ALLOWED_HOSTS = ["127.0.0.1"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',           #add
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('PSQL_DB_NAME'),
        'USER': os.getenv('PSQL_DB_USER'),
        'PASSWORD': os.getenv('PSQL_DB_PASS'),
        # 'HOST': os.getenv('PSQL_DB_HOST', '127.0.0.1'),
        # 'PORT': os.getenv('PSQL_DB_PORT', '5432'),
        'HOST': os.getenv('PSQL_DB_HOST'),
        'PORT': os.getenv('PSQL_DB_PORT'),
        'CONN_MAX_AGE':600,
        'OPTIONS':{
            'connect_timeout':10,
        }
    }
}

CACHES={
    "default":{
        "BACKEND":"django_redis.cache.RedisCache",
        "LOCATION":os.getenv("REDIS_URL_DJANGO"),
 #       "TIMEOUT":600,
        "OPTIONS":{
            "CLIENT_CLASS":"django_redis.client.DefaultClient",
            # "SERIALIZER":"django_redis.serializers.json.JSONSerializer",
            # "CONNECTION_POOL_KWARGS":{
            #     "max_connections":100,
            #     "retry_on_timeout":True,
            # }
            "SOCKET_CONNECT_TIMEOUT":5, #5minutes
            "SOCKET_TIMEOUT":5,
        },
        # "KEY_PREFIX":"prod_arch",
        # "VERSION":1
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR/'staticfiles'
STATICFILES_DIRS = [BASE_DIR/'dist']

LOGGING={
    'version':1,
    'disable_existing_loggers':False,
    'formatters':{
        'verbose':{
            'format':'{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style':'{',
            'datefmt':'%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers':{
        'file_info':{
            'level':'INFO',
            'class':'logging.FileHandler',
            # 'filename':'/var/log/test_django_20260730/django_info.log',
            'filename': os.getenv('DJANGO_LOG'),
            'formatter':'verbose',
        },
    },
    'root':{
        'handlers':['file_info'],
        'level':'INFO',
    },
}

# LOGGING={
#     'version':1,
#     'disable_existing_loggers':False,
#     'fomatters':{
#         'verbose':{
#             'format':'[{levelname}] {asctime} {name} {message}',
#             'style':'{',
#             'datefmt':'%Y-%m-%d %H:%M:%S',
#         },
#     },
#     'handlers':{
#         'django_file':{
#             'level':'ERROR',
#             'class':'logging.FileHandler',
#             'filename':'/var/log/test_django_20260730/django_error.log',
#             'formatter':'verbose',
#         },
#         'django_info':{
#             'level':'INFO',
#             'class':'logging.FileHandler',
#             'filename':'/var/log/test_django_20260730/django_info.log',
#             'formatter':'verbose',
#         },
#     },
#     'loggers':{
#         'django':{
#             'handlers':['django_file','django_info'],
#             'level':'INFO',
#             'propagate':False,
#         },
#         'myapp':{
#             'handlers':['django_file','django_info'],
#             'level':'INFO',
#             'propagate':False,
#         },
#     },
# }


# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}
WHITENOISE_INDEX_FILE = True 